version: "3.7"
services:

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5217
    expose:
      - 5217

  celery:
    container_name: celery_app
    build:
      context: .
    env_file:
      - .env-non-dev
    command: [ "celery", "-A", "distribution.task:celery", "worker", "--loglevel=WARNING" ]
    depends_on:
      - redis

  flower:
    container_name: flower_app
    build:
      context: .
    env_file:
      - .env-non-dev
    command: [ "celery", "-A", "distribution.task:celery", "flower" ]
    depends_on:
      - celery
      - redis
    ports:
      - "9995:5555"

  app:
    container_name: fastapi_app
    build:
      context: .
    env_file:
      - .env-non-dev
    ports:
      - "9991:8000"
    depends_on:
      - redis
      - celery


